export * from './types.js'
export * from './state/store.js'
export { gameStore, getState, setState, dispatch } from './state/store.js'
export * from './logic/move.js'
export const CORE_VERSION = '0.1.0'
